type = "service_account"
project_id = "nimble-willow-433310-n1"
private_key_id = "9e9e63fa1fb463ffba70b73592f2c2dbe2eaad0b"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDE+OseOh12Esei
H/OMxvIp81fu+dLBKwQTY3SMD7tvgsISJkDQ1rsJ1RW7zib8lWn3uWSXRTUcSxu/
HoUoUoZV/6Ssh2Z68K91JtouqK9Hm9hUNErjKaplolw+TBI3gSAa4s2b46IksT7z
Y73QvAE8vF6BuwG7YKD2jVi7MqNVXAGriATr+fgd03+bV4X/4RtoiA9b8+wRERN2
djxmo5+pkwftgWvQL0Zn2CuMTdoel5KDb/d8RYqwLEG+ZCZVgaGPXh6I1JJUSf69
PVtsbXXdMQgRGbk2/wj8H6hBWdHGrjNj6Oa2I1F/lzKY2P6B0a7labMfAhKXI27T
knAQS0DxAgMBAAECggEAAK+FoP6uitJMqdiu4Djyj5kSX6l0tXms+1TLq2+kFUKp
IodJzzhKISIB3/wbGGK8QlGdwyWJZmpwA6mraL0lzM+VnwifH5MuJyweEw7BAnCt
T3i5oIIM/urSY6Cf6RvM1O8gbFgd4L8RsybwGpWG8xNMSGsSWdi/orASBJ/L4ACP
Ce84yH70QlMQY8E7/RVwHB22kvG/1SqcKW0oIBAfgHgjzP68ZyFY7TAKQ+xUA0sX
Ir5xFci7LSXwFlJbFyG+Dl1jKyp6Ptq1umIm9uDxU/tytZ3TYkTxztK8JmgqZLvU
kt5FGHS7ivaDeWhi2cjkOHTMsIkNuxy4GV7NNPoLAQKBgQD54VRHC/YP3bSp7N3V
0Giv9Ocfdu5sy5qcXt2Rvt8SgzG9J/X79O8DfCKXm30gRzD5x9xV8JVLoT4zqthY
SJzk8bDH2fmzXD+txenG1b7fuEc9aOh28QLpLZPB9XpiWj5MvJbBOYclRYfQIO2V
UZBxaF9Vaa59eHoUEdcQsNw6cQKBgQDJy9+dFlDFkhlDlD7H0LpFhGEt/98sCwhn
D2Iur+fT4nf+c5Ve5KYtR3xmHMGl7SrrZlftCkgRLxCUKuVCEiGLij4QWJAQZM18
NMK1PN7jqOG4oSOm4il8ggyPlpCvXHmn3lfwNa8cb9ytCs2F5KfqMkB9CMwPQKn1
hNL9/amugQKBgQClzsYciqxRJN0/sCQXP75nm4tNjp5w5L2IK0686jmdUB7OFFke
Qg3jcxiFHzDtHTA7XkovYH/AepMKt7/s/OnW5SVXx6TwRjMe/Oe9/5EzZFUpQ5aV
biFvVsXn+xqlbppOUwl519F8guG20lK0NTYyen5f78tQCISBEsFxmtnXkQKBgQCR
tphqmwGKGHwLs1E+AbdvmS5/A8NHz1Oq743K/pQdCOvync2fLuXbzkHCjkM6qC4U
utsEvCbb2atUAkF3WxZD53f3X6vvWoqShJqQOjsMExeitSDEUYz5bgLZ8DPbnJ/w
GnpPZsRieVfUz/cmFr01PEIaxy5qWRwgwF+GrhNHgQKBgCYPeBoAuZigr8UqlgZq
VN2yGCFq6j+yAnBttTPfHRUEJymYh1O7Y1JGZoS88OvfKF8OSU9XAGlzqJbrGIZG
RKDbx/GcCwwVHsOciGhWrweqiaZF3x9mR56zH1s1fJfAO7EWRpAcxwLUMirK9X1Y
mzTyBiET6P8qXKHkKPTZZECV
-----END PRIVATE KEY-----
"""
client_email = "bhanusheet@nimble-willow-433310-n1.iam.gserviceaccount.com"
client_id = "114880791889927291887"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/bhanusheet@nimble-willow-433310-n1.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

# Spreadsheet configuration
sheet_name = "Sheet1"
spreadsheet_id = "1OuiQ3FEoNAtH10NllgLusxACjn2NU0yZUcHh68hLoI4"
spreadsheet_name = "bhanu"

# Database configuration
DATABASE_URL = "postgresql://bhanu123_owner:BrCH2kpXAz1j@ep-falling-scene-a1pn8mnr.ap-southeast-1.aws.neon.tech/bhanu123?sslmode=require"

NOTIFICATION_RECIPIENTS = ["+919490100101", "+919704503707"]
TELEGRAM_BOT_TOKEN = "7820521627:AAEWznwufb6tN_p5tEWRUv_qqip2R96qH0Q"
TELEGRAM_CHAT_IDS = "7089282858,998524115"
TELEGRAM_CHANNEL_ID = "@operatingBZA"